# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: derthorstenbeier@gmail.com
author_name: Thorsten Beier
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlite_polyglott
project_short_description: A JupyterLite polyglott meta kernel
python_name: jupyterlite_polyglott
repository: https://github.com/DerThorsten/jupyterlite-polyglott
test: false

